/** 目录中文标注映射（供 label-all / label-fix 共用） */

export const SPECIAL = {
  '.': '项目说明与开源协议',
  scripts: '开源仓维护脚本',
  'admin-art': '管理后台前端源码（Vue3）',
  'admin-art/.husky': 'Git 提交钩子',
  'admin-art/public': '管理端公共静态文件',
  'admin-art/scripts': '管理端工具脚本',
  'admin-art/src': '管理端前端源码',
  'admin-art/src/api': '管理端 API 封装',
  'admin-art/src/assets': '管理端静态素材',
  'admin-art/src/assets/images': '管理端图片素材',
  'admin-art/src/assets/styles': '全局样式',
  'admin-art/src/assets/styles/core': '核心样式',
  'admin-art/src/assets/styles/custom': '自定义样式',
  'admin-art/src/assets/svg': 'SVG 资源',
  'admin-art/src/components': '通用组件',
  'admin-art/src/components/business': '业务组件',
  'admin-art/src/components/core': '核心 UI 组件',
  'admin-art/src/components/core/banners': '横幅组件',
  'admin-art/src/components/core/base': '基础组件',
  'admin-art/src/components/core/cards': '卡片组件',
  'admin-art/src/components/core/charts': '图表组件',
  'admin-art/src/components/core/forms': '表单组件',
  'admin-art/src/components/core/layouts': '布局组件',
  'admin-art/src/components/core/media': '媒体组件',
  'admin-art/src/components/core/others': '其他组件',
  'admin-art/src/components/core/tables': '表格组件',
  'admin-art/src/components/core/text-effect': '文字动效组件',
  'admin-art/src/components/core/theme': '主题组件',
  'admin-art/src/components/core/views': '视图组件',
  'admin-art/src/components/core/widget': '小组件',
  'admin-art/src/components/xhamil': 'XhaMil 业务组件',
  'admin-art/src/config': '前端配置',
  'admin-art/src/config/assets': '资源配置',
  'admin-art/src/config/modules': '配置模块',
  'admin-art/src/data': '预设数据',
  'admin-art/src/directives': 'Vue 指令',
  'admin-art/src/directives/business': '业务指令',
  'admin-art/src/directives/core': '核心指令',
  'admin-art/src/enums': '枚举定义',
  'admin-art/src/hooks': '组合式函数',
  'admin-art/src/hooks/core': '核心 Hooks',
  'admin-art/src/locales': '国际化',
  'admin-art/src/locales/langs': '中英文语言包',
  'admin-art/src/mock': '本地 Mock 数据',
  'admin-art/src/mock/json': 'Mock JSON',
  'admin-art/src/mock/temp': '临时 Mock',
  'admin-art/src/mock/upgrade': '升级日志 Mock',
  'admin-art/src/plugins': '插件注册',
  'admin-art/src/router': '路由',
  'admin-art/src/router/core': '路由核心',
  'admin-art/src/router/guards': '路由守卫',
  'admin-art/src/router/modules': '路由模块',
  'admin-art/src/router/routes': '静态路由',
  'admin-art/src/store': '状态管理',
  'admin-art/src/store/modules': 'Store 模块',
  'admin-art/src/types': 'TypeScript 类型',
  'admin-art/src/types/api': 'API 类型',
  'admin-art/src/types/common': '通用类型',
  'admin-art/src/types/component': '组件类型',
  'admin-art/src/types/config': '配置类型',
  'admin-art/src/types/directive': '指令类型',
  'admin-art/src/types/router': '路由类型',
  'admin-art/src/types/store': 'Store 类型',
  'admin-art/src/utils': '工具函数',
  'admin-art/src/utils/constants': '常量',
  'admin-art/src/utils/form': '表单工具',
  'admin-art/src/utils/http': 'HTTP 工具',
  'admin-art/src/utils/navigation': '导航工具',
  'admin-art/src/utils/socket': 'Socket 工具',
  'admin-art/src/utils/storage': '本地存储工具',
  'admin-art/src/utils/sys': '系统工具',
  'admin-art/src/utils/table': '表格工具',
  'admin-art/src/utils/ui': 'UI 工具',
  'admin-art/src/views': '页面视图',
  'admin-art/src/views/article': '文章示例页',
  'admin-art/src/views/auth': '登录注册页',
  'admin-art/src/views/auth/forget-password': '忘记密码页',
  'admin-art/src/views/auth/login': '登录页',
  'admin-art/src/views/auth/register': '注册页',
  'admin-art/src/views/change': '变更相关页',
  'admin-art/src/views/change/log': '变更日志页',
  'admin-art/src/views/dashboard': '仪表盘示例页',
  'admin-art/src/views/dashboard/analysis': '分析仪表盘',
  'admin-art/src/views/dashboard/console': '控制台仪表盘',
  'admin-art/src/views/dashboard/ecommerce': '电商仪表盘',
  'admin-art/src/views/examples': '示例页',
  'admin-art/src/views/examples/forms': '表单示例',
  'admin-art/src/views/examples/permission': '权限示例',
  'admin-art/src/views/examples/socket-chat': 'Socket 聊天示例',
  'admin-art/src/views/examples/tables': '表格示例',
  'admin-art/src/views/examples/tabs': '标签页示例',
  'admin-art/src/views/exception': '异常页',
  'admin-art/src/views/exception/403': '403 页',
  'admin-art/src/views/exception/404': '404 页',
  'admin-art/src/views/exception/500': '500 页',
  'admin-art/src/views/index': '首页',
  'admin-art/src/views/outside': '外链页',
  'admin-art/src/views/result': '结果页',
  'admin-art/src/views/result/fail': '失败结果页',
  'admin-art/src/views/result/success': '成功结果页',
  'admin-art/src/views/safeguard': '运维保障页',
  'admin-art/src/views/safeguard/server': '服务器监控页',
  'admin-art/src/views/system': '系统管理示例页',
  'admin-art/src/views/system/menu': '菜单管理',
  'admin-art/src/views/system/nested': '嵌套菜单示例',
  'admin-art/src/views/system/role': '角色管理',
  'admin-art/src/views/system/user': '用户管理示例',
  'admin-art/src/views/system/user-center': '个人中心',
  'admin-art/src/views/template': '模板页',
  'admin-art/src/views/widgets': '控件示例页',
  'admin-art/src/views/xhamil': 'XhaMil 业务管理页',
  'admin-art/src/views/xhamil/analysis': '数据分析',
  'admin-art/src/views/xhamil/app-docs': 'App 说明文档配置',
  'admin-art/src/views/xhamil/app-update': 'App 发版更新',
  'admin-art/src/views/xhamil/avatars': '头像管理',
  'admin-art/src/views/xhamil/banned-words': '违禁词',
  'admin-art/src/views/xhamil/changelog': '更新日志',
  'admin-art/src/views/xhamil/chat-photos': '聊天图片管理',
  'admin-art/src/views/xhamil/chat-videos': '聊天视频管理',
  'admin-art/src/views/xhamil/chat-voice': '聊天语音管理',
  'admin-art/src/views/xhamil/database': '数据库管理',
  'admin-art/src/views/xhamil/database-browse': '数据库浏览',
  'admin-art/src/views/xhamil/download-page': '官方下载页配置',
  'admin-art/src/views/xhamil/error-codes': '错误码',
  'admin-art/src/views/xhamil/functional-dev': '功能开发开关',
  'admin-art/src/views/xhamil/group-ai': '群聊 AI',
  'admin-art/src/views/xhamil/group-announcement-images': '群公告图片',
  'admin-art/src/views/xhamil/group-files': '群文件管理',
  'admin-art/src/views/xhamil/groups': '群组管理',
  'admin-art/src/views/xhamil/icons': '图标资源管理',
  'admin-art/src/views/xhamil/media': '媒体浏览器',
  'admin-art/src/views/xhamil/moments': '说说管理',
  'admin-art/src/views/xhamil/moments-photos': '说说图片',
  'admin-art/src/views/xhamil/moments-videos': '说说视频',
  'admin-art/src/views/xhamil/public-voice-rooms': '公开语音房',
  'admin-art/src/views/xhamil/reports': '举报处理',
  'admin-art/src/views/xhamil/users': '用户管理',
  'admin-art/src/views/xhamil/verification': '实名/验证配置',
  'admin-art/src/views/xhamil/workbench': '工作台',
  backend: 'Node 后端 API 与管理端静态资源',
  'backend/data': '运行时数据目录（敏感文件已忽略）',
  'backend/pack': '打包相关',
  'backend/pack/tools': 'App 打包工具',
  'backend/public': '对外静态资源',
  'backend/public/admin': '管理后台构建产物',
  'backend/public/admin/assets': '管理后台静态资源文件',
  'backend/public/desktop-map': '桌面端地图页',
  'backend/public/desktop-map/leaflet': 'Leaflet 地图库',
  'backend/public/download': '官方下载页',
  'backend/public/download/promo': '下载页宣传图',
  'backend/public/download/vendor': '下载页第三方脚本',
  'backend/public/pack': '免费打包页',
  'backend/public/pack/img': '打包页图片',
  'backend/public/password-reset': '密码重置页',
  'backend/scripts': '运维与清理脚本',
  'backend/src': '后端业务源码',
  'backend/src/data': '后端内置数据',
  'backend/src/routes': 'HTTP 路由',
  deploy: '进程启动脚本（宝塔等）',
  docs: '部署与运维文档',
  json: '配置模板（复制 config.example 为 config.json）',
  media: '媒体资源根目录（默认素材 + 上传占位）',
  'media/About Page': '关于页开发者/鸣谢头像（运行时上传）',
  'media/App Releases': 'App 安装包上传目录（运行时）',
  'media/Audio': '聊天语音上传目录（运行时）',
  'media/Avatar Frames': '头像框资源',
  'media/Chat Bubbles': '聊天气泡皮肤',
  'media/Chat Images': '聊天图片上传目录（运行时）',
  'media/Chat Videos': '聊天视频上传目录（运行时）',
  'media/Default Avatars': '用户默认头像池',
  'media/Download Page': '下载页旧资源占位（运行时）',
  'media/Group Files': '群文件上传目录（运行时）',
  'media/Moments': '说说图片上传目录（运行时）',
  'media/Moments Videos': '说说视频上传目录（运行时）',
  'media/Notification sound': '客户端通知提示音',
  'media/Official Images': '官方默认图（登录/语音房/Logo等）',
  'media/Reports': '举报截图上传目录（运行时）',
  'media/Sticker': '表情贴纸目录',
  'media/Sticker/builtin-official': '内置官方表情包',
  'media/Tts': 'TTS 语音缓存目录（运行时）',
  'media/avatar': '用户头像（含 default.png）',
  'media/vosk': '语音识别模型说明（模型文件需自备）'
}

export const TOP_LAST = [
  'media/Sticker/builtin-official',
  'media/Sticker',
  'media',
  'json',
  'docs',
  'deploy',
  'scripts',
  'admin-art',
  'backend'
]

export function labelFor(dir) {
  if (SPECIAL[dir]) return SPECIAL[dir]
  const base = dir.split('/').pop()
  if (dir.includes('/modules')) return `子模块：${base}`
  if (dir.includes('/widget')) return `子组件：${base}`
  if (dir.startsWith('admin-art/src/assets/images/')) return `管理端图片：${base}`
  if (dir.startsWith('admin-art/src/components/')) return `组件：${base}`
  if (dir.startsWith('admin-art/src/views/')) return `页面：${base}`
  if (dir.startsWith('admin-art/src/')) return `源码：${base}`
  if (dir.startsWith('admin-art/')) return `管理端：${base}`
  if (dir.startsWith('backend/public/')) return `静态资源：${base}`
  if (dir.startsWith('backend/src/')) return `后端源码：${base}`
  if (dir.startsWith('backend/')) return `后端：${base}`
  if (dir.startsWith('media/')) return `媒体目录：${base}`
  return `目录：${base}`
}
